# Generated by Django 5.0.6 on 2024-11-22 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('player_id', models.AutoField(primary_key=True, serialize=False)),
                ('player_name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('team', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('Batsman', 'Batsman'), ('Bowler', 'Bowler')], max_length=10)),
                ('average', models.FloatField()),
                ('photograph', models.ImageField(blank=True, null=True, upload_to='player_photos/')),
            ],
        ),
    ]
