# Generated by Django 5.0.6 on 2024-11-23 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('team_name', models.CharField(max_length=100, verbose_name='Team Name')),
                ('format', models.CharField(choices=[('T20', 'T20'), ('ODI', 'ODI'), ('Test', 'Test')], max_length=10, verbose_name='Match Format')),
                ('team_logo', models.ImageField(upload_to='team_logos/', verbose_name='Team Logo')),
                ('date', models.DateField(verbose_name='Match Date')),
                ('time', models.TimeField(verbose_name='Match Time')),
                ('venue', models.CharField(max_length=200, verbose_name='Match Venue')),
            ],
            options={
                'verbose_name': 'Match',
                'verbose_name_plural': 'Matches',
                'ordering': ['date', 'time'],
            },
        ),
    ]
