# Generated by Django 5.0.6 on 2024-11-23 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_match'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='team_logo',
            field=models.ImageField(blank=True, null=True, upload_to='team_logos/'),
        ),
    ]
